### ISSUE TITLE
XkbCommonConfig.cmake not found

### ISSUE THREAD

**Issue by skaendo** [qmlos/shell#224] opened 2022-11-29 01:38 UTC
Getting a fatal error that cmake cannot find XkbCommonConfig.cmake.
I believe that the file "FindXkbCommon.cmake" is missing from the source tarball? Or libxkbcommon should be found by pkgconfig?
I'm building from git.
Here is the error:

> CMake Error at /usr/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindXkbCommon.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "XkbCommon", but CMake did not find one.
>
>  Could not find a package configuration file provided by "XkbCommon" with
  any of the following names:
>
>    XkbCommonConfig.cmake
>    xkbcommon-config.cmake
>
>  Add the installation prefix of "XkbCommon" to CMAKE_PREFIX_PATH or set
  "XkbCommon_DIR" to a directory containing one of the above files.  If
  "XkbCommon" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/Liri1AuroraXkbCommonSupport/Liri1AuroraXkbCommonSupportDependencies.cmake:9 (find_dependency)
  /usr/lib64/cmake/Liri1AuroraXkbCommonSupport/Liri1AuroraXkbCommonSupportConfig.cmake:42 (include)
  /usr/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/lib64/cmake/Liri1AuroraCompositor/Liri1AuroraCompositorDependencies.cmake:10 (find_dependency)
  /usr/lib64/cmake/Liri1AuroraCompositor/Liri1AuroraCompositorConfig.cmake:42 (include)
  src/compositor/CMakeLists.txt:21 (find_package)
>
>
>-- Configuring incomplete, errors occurred!

**Comment by plfiorini** [comment] 2022-11-30 06:18
Duplicate of lirios/aurora-compositor#30

**Closed as completed by plfiorini** 2022-11-30 06:18 UTC
